
version: '3.8'
services:
  vprodb: 
    build:
      context: ./Docker-files/db 
    image: an18041999/vprofile-db
    container_name: vprodb
    ports: 
      - "3306:3306"
    volumes: 
      - vprofiledb:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=admin123

  vprocache01: 
    image: memcached    
    container_name: vprocache01
    ports: 
      - "11211:11211"

  vpromq01: 
    image: rabbitmq
    container_name: vpromq01
    ports: 
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    
  vproapp:
    build:
      context: ./Docker-files/app 
    image: an18041999/vprofile-app
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vprofilewapp:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web 
    image: an18041999/vprofile-web
    container_name: vproweb
    ports: 
      - "80:80"

volumes: 
  vprofiledb: {}
  vprofilewapp: {}


